services:
  - type: web
    name: lens-and-light-studio
    env: python
    buildCommand: pip install -r requirements.txt && python seed_db.py
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
